// src/components/tiles/article/index.tsx
import Link from 'next/link';
import React from 'react';
import styled from 'styled-components';
import { Article } from '../../../data/articles';

type Props = {
  article: Article;
}

const Wrapper = styled.div`
  cursor: pointer;
  display: flex;
  padding: 15px;
`;

const Inner = styled.div`
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
`;

const ImageWrapper = styled.div`
  width: 160px;
  max-height: 100%;
  position: relative;
  margin-left: 20px;
`;

const Header = styled.h3`
  margin: 0;
  font-weight: 600;
`;

const Published = styled.time`
  display: block;
  font-size: 0.8rem;
  padding-bottom: 1rem;
`;

const Image = styled.div<{
  src: string
}>`
  position: absolute; 
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-image: url('${({src}) => src}');
  background-size: cover;
  background-position: center;
`;

const ArticleTile: React.FC<Props> = ({ article }) => (
  <Link href={`/articles/${article.id}`}>
    <Wrapper>
      <Inner>
        <Header>
          {article.title}
        </Header>
        <Published>3 days ago</Published>
      </Inner>
      <ImageWrapper>
        <Image src={article.cover} />
      </ImageWrapper>
    </Wrapper>
  </Link>
);

export { ArticleTile };

// src/lib/components/articles/article.svelte
<script>
	import Color from '$lib/components/color.svelte';
	import Img from '@zerodevx/svelte-img';
	export let article;
</script>

<Color color={article.color}>
	<a href={article.url} class="root">
		<Img class="aside" src={article.thumbSet} alt={article.title} />
		<div class="meta">
			{#each article.title.split(' ') as word}
				<span class="word">
					{word}
				</span>
			{/each}
		</div>
	</a>
</Color>

<style module>
	.root {
		position: relative;
		margin: 15px;
		cursor: pointer;
		display: flex;
		width: 220px;
		height: 200px;

		@media only screen and (max-width: 700px) {
			width: 100%;
		}
	}

	.word {
		line-height: 20px;
		font-size: 20px;
		padding: 5px 5px;
		font-family: 'Black Ops One', sans-serif;
		margin: 5px 0;
		background: var(--primary);
		color: var(--primary-alt);
	}

	.meta {
		display: flex;
		flex-direction: row;
		flex-wrap: wrap;
		padding: 10px;
		max-width: 220px;
		position: absolute;
	}

	.aside {
		background-size: cover;
		background-position: center;
		object-fit: cover;
		object-position: center;
		position: absolute;
		top: 0;
		left: 0;
		width: 100%;
		height: 100%;
	}
</style>
